import React, { useContext } from "react";
import Button from "../../../components/reusable/button";
import { UploadAttachmentsContext } from "./upload-attachments-context";

export default function WaitingWrapper({
  children,
  nextStep,
}: {
  children: React.ReactNode;
  nextStep: number;
}) {
  const { setCurrentPageId, setCurrentStep } = useContext(UploadAttachmentsContext);
  const handleContinueBtnClick = () => {
    console.log("nextStep", nextStep);
    setCurrentPageId(nextStep);
    setCurrentStep((prev) => prev + 1);
  };

  return (
    <div className="flex flex-row justify-between gap-x-[150px]">
      <div className="flex flex-col min-w-[900px] min-h-[400px] bg-white rounded-lg">
        <p className="font-bold text-[32px] text-secondary-900">Here's a sneak peek!</p>
        <p className="font-semibold text-xl text-secondary-800">
          This summary is based on your report, generated by our AI.
        </p>
        <div className="text-gray-600 mt-[20px]">
          {summary.map((item) => (
            <div key={item.heading} className="mb-2">
              <p className="text-base font-bold">
                {item.heading}
                {":"}
              </p>
              <ul className="list-disc pl-[20px] text-sm">
                {item.list.map((content) => (
                  <li key={content} className="text-sm">
                    {content}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      <div className="w-[300px] space-y-5">
        <>
          {children}
          <Button type="optional" classname="w-full" handleClick={handleContinueBtnClick}>
            <p className="text-secondary-800">Continue</p>
          </Button>
          <p className="cursor-pointer underline text-purple-900">
            If more info is required (temp link)
          </p>
        </>
      </div>
    </div>
  );
}

const summary = [
  // TODO fetch from BE
  {
    heading: "Prior Art & Novelty",
    list: [
      "We checked existing inventions to see how unique yours is.",
      "There are some similar ones, but yours might be new due to [mention specific features].",
      "We recommend looking closer at specific patents for a deeper dive.",
    ],
  },
  {
    heading: "Licensing Targets",
    list: [
      "Companies in [mention specific industries] could be interested in licensing your tech based on its features and market trends.",
      "We can refine this list with further market analysis.",
    ],
  },

  {
    heading: "Patent Validity (Initial)",
    list: [
      "Our analysis suggests your patent has a good chance of being valid because [brief explanation].",
      "However, a more thorough analysis is recommended for extra confidence.",
    ],
  },
];
