// Define all options for all sections
const allOptions = {
  agents: [
    "Startup diligence",
    "Portfolio support",
    "Fundraising strategy",
    "Market strategy",
    "Technology & R&D",
    "Product & Engineering",
    "Marketing & Sales",
    "Finance & Strategy",
    "Legal & Compliance",
    "Report on Anything",
    "Corporate Development",
  ],
  datasets: [
    "Custom Dataset Integration",
    "Real-Time Market Insights",
    "Predictive Analytics",
    "AI-Augmented Cross-Validation",
    "Historical and Trend Analysis",
    "Hybrid Data Layering",
    "Proprietary Knowledge Graphs",
    "Verified Multi-Source Insights",
  ],
  reportDesignCustomization: [
    "Font & Color Customization",
    "Logo & Branding Integration",
    "Layout & Design Flexibility",
  ],
  reportContentCustomization: [
    "Report Tone",
    "Charts and Visuals",
    "Visual Style",
    "Citation Style",
  ],
  knowNowChat: [
    "Hyper-specialized for market and patent",
    "Delivers strategic recommendations",
    "Interactive visual-first insights",
    "Predictive scenario modeling",
    "Fine-tuned for key industries",
    "Streamlined for team collaboration",
    "Context-aware responses",
    "Predictive Modeling",
  ],
  quickViewReports: [
    "Single-Page Summaries",
    "Simplified Tone",
    "Investor-Centric Insights",
    "Stakeholder-Specific Reports",
  ],
  explainability: [
    "Basic Stat Explanations",
    "Source Citations",
    "Logical Breakdown Layers",
    "Editable Data & Metrics",
    "Advanced Multi-Layered Insights",
    "Forecasting Transparency",
  ],
  templates: [
    "UI-based options for pre-built templates",
    "Semi-customizable templates tailored to professional goals",
    "Fully UI-customizable templates for enterprise-wide insights",
  ],
  dynamicSectionCustomization: [
    "Add/remove key metrics (e.g., market, competitors, funding strategy)",
    "Enhanced customization with UI-based smart options",
    "Fully customizable sections through advanced UI tools",
  ],
  reportFormats: ["pdf", "docx", "csv", "xlsx", "pptx"],
};

const descriptions = {
  agents: [
    "Detailed reports to evaluate startups, assess risks, and identify growth opportunities.",
    "Insights to optimize and manage investment portfolios effectively.",
    "Data-driven strategies to help raise funds from investors with confidence.",
    "Actionable insights to understand markets and stay ahead of competitors.",
    "Reports focused on innovation, research, and development trends in your industry.",
    "Data to guide product development and improve engineering processes.",
    "Insights to craft marketing strategies and drive sales performance.",
    "Financial data and analysis for informed decision-making and planning.",
    "Reports focused on legal and compliance requirements for smooth operations.",
    "Fully customizable reports based on unique needs and specifications.",
    "Strategic reports for high-level corporate growth and decision-making.",
  ],
  datasets: [
    "Allows users to upload and integrate their own datasets for analysis.",
    "Provides up-to-date market and real-time industry activity tracking.",
    "AI-powered analysis to forecast trends and predict future scenarios.",
    "Cross-checks data against internal and external sources to ensure accuracy.",
    "Analyzes historical data to identify patterns and predict future outcomes.",
    "Combines static, real-time, and curated datasets for deeper insights.",
    "Vast maps connecting datasets for a broader understanding of market and patent landscapes.",
    "Aggregates insights from multiple trusted sources for enterprise-grade reliability.",
  ],
  reportDesignCustomization: [
    "Customize the look of your reports with specific fonts and color schemes.",
    "Add your logo and branding for a professional, personalized touch.",
    "Fully flexible layouts and advanced design options for unique needs.",
  ],
  reportContentCustomization: [
    "Our report content customization options allow you to create reports that reflect your brand and style.",
    "Our report content customization options allow you to create reports that reflect your brand and style.",
    "Our report content customization options allow you to create reports that reflect your brand and style.",
    "Our report content customization options allow you to create reports that reflect your brand and style.",
  ],
  knowNowChat: [
    "AI tool specializing in delivering insights from market and patent datasets.",
    "Provides actionable suggestions based on in-depth analysis.",
    "Presents insights through interactive, visual dashboards for easy understanding.",
    "Simulates and predicts outcomes based on data analysis.",
    "Optimized insights for industries like healthcare, aerospace, and technology.",
    "Designed for team-wide use, making collaboration seamless.",
    "AI adapts its answers to your specific context and needs.",
    "Forecasts trends and opportunities with high accuracy.",
  ],
  quickViewReports: [
    "Condensed reports that highlight only the most important details.",
    "Simplifies technical data for easy understanding by all stakeholders.",
    "Reports tailored specifically to the interests of investors.",
    "Designed to address the specific needs of various stakeholders.",
  ],
  explainability: [
    "Explains statistical data clearly for better understanding.",
    "Includes references for transparency and credibility.",
    "Breaks down complex data into logical, easy-to-follow layers.",
    "Enables customization of data and metrics for tailored analysis.",
    "In-depth data exploration for power users seeking advanced insights.",
    "Provides clear explanations for forecasting methodologies.",
  ],
  templates: [
    "Our templates are designed to provide you with the most accurate and up-to-date information available.",
    "Our templates are designed to provide you with the most accurate and up-to-date information available.",
    "Our templates are designed to provide you with the most accurate and up-to-date information available.",
  ],
  dynamicSectionCustomization: [
    "Our dynamic section customization options allow you to create reports that reflect your brand and style.",
    "Our dynamic section customization options allow you to create reports that reflect your brand and style.",
    "Our dynamic section customization options allow you to create reports that reflect your brand and style.",
  ],
  reportFormats: [
    "Standard format for easy sharing and printing.",
    "Editable report formats in Word documents.",
    "Exportable data for deeper analysis in spreadsheets.",
    "Advanced spreadsheet format for data manipulation.",
    "Presentation-ready formats for sharing insights.",
  ],
};

export { descriptions };

export default allOptions;
