name: Build and deploy Node.js app to Azure Web App - perceivenowfrontend

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Archive build files
        run: zip -r build.zip build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Unzip artifact for deployment
        run: unzip build.zip -d ./build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'perceivenowfrontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./build


      - name: Install PM2 globally
        run: npm install pm2 -g

      - name: Serve the application with PM2
        run: |
          pm2-runtime serve /home/site/wwwroot/build --spa --no-daemon

